### ISSUE TITLE
Fix PDSView build and execution error related to libc6 dependency

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS-Incubator/pds-view#21]
**Describe the bug**
The latest release (0.4.0) is built against a specific version of libc6, which is not installed on my system, resulting in the error:

```
$ ./PDSView 
[12633] Error loading Python lib '/tmp/_MEIm2ZnrJ/libpython2.7.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIm2ZnrJ/libpython2.7.so.1.0)
```

** Version of PDS View **
Version: 0.4.0

**To Reproduce**
1. Unzip the linux zip file
2. make executable
3. execute

**Desktop (please complete the following information):**
 - OS: linux
 - Version : ubuntu 18.04

**Comment by jordanpadams** [comment]
@msbentley thanks for testing this out. Update to come ASAP.

**Comment by jordanpadams** [comment]
@nutjob4life if you have a chance, can you try to triage this asap?

**Comment by nutjob4life** [comment]
OK, I've tried to make a single Linux-based distribution that would work out of the box for multiple distributions, but in the end I didn't have enough hair left to pull out, and there was that "asap" to contend with.

So, I renamed the `PDSView-linux.zip` asset to `PDSView-debian-10.zip`, and then created and uploaded a new asset: `PDSView-ubuntu-18.04.zip`. That one works for me on Ubuntu 18.04 with its built-in `libc`. Hope it works for you, too.

**Comment by msbentley** [comment]
Thanks @nutjob4life - that solution is fine with me. I tried running it, but rather than the GUI that I saw from the old version I get a file browse selector - is that correct? If I choose a PDS4 label, it opens the GUI OK. If I choose a PDS3 label (actually the example provided in the old nasaview distribution), it crashes out with:

```
$ ./PDSView 
DEBUG:./logfile:2019-09-12 09:28:42,319:Initializing logger
DEBUG:./logfile:2019-09-12 09:28:42,319:Parsing header
DEBUG:./logfile:2019-09-12 09:28:42,320:Parsed 33 top-level labels
Traceback (most recent call last):
  File "bin/PDSView", line 21, in <module>
  File "/home/kelly/pds-view/eggs/PyInstaller-3.4-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "pds_view/View.py", line 3072, in <module>
  File "pds_view/View.py", line 3067, in main
  File "pds_view/View.py", line 3048, in __init__
  File "pds_view/View.py", line 699, in __init__
  File "pds_view/View.py", line 1158, in file_open
  File "pds_view/View.py", line 1138, in pds_file_check
  File "pds_view/Translate.py", line 215, in convert_to_pds4
  File "eggs/airspeed-0.5.11-py2.7.egg/airspeed/__init__.py", line 186, in load_template
  File "genericpath.py", line 62, in getmtime
OSError: [Errno 2] No such file or directory: '/tmp/_MEIPDn4Wj/./templates/InspectTemplate.vm'
[8515] Failed to execute script PDSView
```

**Comment by msbentley** [comment]
Ahh, sorry I missed that opening the file dialogue was expected behaviour for the new version - should I open the above issue as a new ticket for PDS3?

**Comment by jordanpadams** [comment]
@msbentley that would be great! Thanks for testing it out!

**Comment by jordanpadams** [comment]
@nutjob4life thanks!
