### ISSUE TITLE
PDSView fails on PDS3 attached product (fails to find InspectTemplate.vm)

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS-Incubator/pds-view#22]
**Describe the bug**
When attempting to open the example product provided with nasaview-3.18.0_linux64 (FHA01118.LBL) PDS View crashes with the output:

```
DEBUG:./logfile:2019-09-12 15:50:51,664:Initializing logger
DEBUG:./logfile:2019-09-12 15:50:51,665:Parsing header
DEBUG:./logfile:2019-09-12 15:50:51,666:Parsed 33 top-level labels
Traceback (most recent call last):
  File "bin/PDSView", line 21, in <module>
  File "/home/kelly/pds-view/eggs/PyInstaller-3.4-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "pds_view/View.py", line 3072, in <module>
  File "pds_view/View.py", line 3067, in main
  File "pds_view/View.py", line 3048, in __init__
  File "pds_view/View.py", line 699, in __init__
  File "pds_view/View.py", line 1158, in file_open
  File "pds_view/View.py", line 1138, in pds_file_check
  File "pds_view/Translate.py", line 215, in convert_to_pds4
  File "eggs/airspeed-0.5.11-py2.7.egg/airspeed/__init__.py", line 186, in load_template
  File "genericpath.py", line 62, in getmtime
OSError: [Errno 2] No such file or directory: '/tmp/_MEIDvAaXA/./templates/InspectTemplate.vm'
[30634] Failed to execute script PDSView
```

** Version of PDS View **
Version: v0.4.0 ubuntu package

**To Reproduce**
1. Start PDS View
2. Select product FHA01118.LBL ([FHA01118.zip](https://github.com/NASA-PDS-Incubator/pds-view/files/3605829/FHA01118.zip))

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version: 18.04

**Comment by nutjob4life** [comment]
@msbentley I created a new release of `PDSView-ubuntu-18.04.zip` which you can download from the releases tab. Please try this one and let me know if it works.
If it does, I'll need to make the same fix to the Debian release.

**Comment by msbentley** [comment]
Yes, that works for me now - many thanks!

**Comment by nutjob4life** [comment]
Fantastic, thank you so much 😌

I will fix the Debian release as well.

**Comment by rchenatjpl** [comment]
This didn't work for me. I downloaded FHA01118.zip, uncompressed it, started PDSView.app, tried to open FHA01118.LBL, and the app stopped. NASAView viewed the .LBL successfully (some crater?). For you suspicious types, which is fine, a screen capture is in my home directory on pds-gamma named view22.mov. FYI, thanks for including a test file.
