### ISSUE TITLE
PDS3 binary table not opened correctly

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS-Incubator/pds-view#24]
**Describe the bug**
Attempting to open a PDS3 binary table fails when clicking View in the GUI, with the following errors:

```
(base) mbentley@bpcl03:~/Desktop/psa_data$ ~/Dropbox/software/pds/PDSView 
DEBUG:./logfile:2019-09-18 15:52:47,604:Initializing logger
DEBUG:./logfile:2019-09-18 15:52:47,604:Parsing header
DEBUG:./logfile:2019-09-18 15:52:47,605:Parsed 43 top-level labels
Processing label: /home/mbentley/Desktop/psa_data/MIRO_4_MM1S_2016272.xml
Found a Table_Binary structure: DESCRIPTION_0
Warning: <fields> value does not match number of <Field_Binary> in Record_Binary.
Error: min() arg is an empty sequence
Traceback (most recent call last):
  File "pds_view/View.py", line 1509, in handle_view_clicked
  File "pds_view/View.py", line 1755, in draw_table
  File "pds_view/Model.py", line 301, in get_table
  File "eggs/pds4_tools-1.0-py2.7.egg/pds4_tools/extern/cached_property.py", line 86, in __get__
  File "eggs/pds4_tools-1.0-py2.7.egg/pds4_tools/reader/table_objects.py", line 368, in data
  File "eggs/pds4_tools-1.0-py2.7.egg/pds4_tools/reader/read_tables.py", line 951, in read_table_data
  File "eggs/pds4_tools-1.0-py2.7.egg/pds4_tools/reader/read_tables.py", line 709, in new_table
ValueError: min() arg is an empty sequence
```
I have attached the PDS3 product, the corresponding format file (which is in the same directory as the product) and the failing auto-generated PDS4 label (in which the fields are not defined). Note that if I use transform 1.7 on this label, I get a correct PDS4 label that works correctly with the data file.

**Version of PDS View**
Version: 0.4.0 ubuntu

**To Reproduce**
Load the attached product and click View on the table.

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04

[MIRO_4_MM16_2016272.zip](https://github.com/NASA-PDS-Incubator/pds-view/files/3626763/MIRO_4_MM16_2016272.zip)

**Comment by msbentley** [comment]
And here is the PDS4 label generated with transform 1.7

[miro_4_mm1s_2016272.xml.txt](https://github.com/NASA-PDS-Incubator/pds-view/files/3626775/miro_4_mm1s_2016272.xml.txt)
