### ISSUE TITLE
'offset' referenced before assignment error for Rosetta/MIDAS PDS3 product

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS-Incubator/pds-view#8]
Attempting to open the following PDS3 product from the PSA (Rosetta/MIDAS):

http://psa.esa.int/pdap/download?RESOURCE_CLASS=PRODUCT&ID=RO-C-MIDAS-5-PRL-TO-EXT3-V1.0:DATA:IMG_1612423_1615300_069_ZS::1.0

results in no message/warning/error from the GUI but the following reports in the terminal:

```
Traceback (most recent call last):
  File "pds_inspect_tool/View.py", line 1155, in file_open
  File "pds_inspect_tool/View.py", line 1135, in pds_file_check
  File "pds_inspect_tool/Translate.py", line 204, in convert_to_pds4
UnboundLocalError: local variable 'offset' referenced before assignment
```

**Comment by msbentley** [comment]
Just to note that this is still an issue on version 0.4.0:

```
$ ~/Dropbox/software/pds/PDSView 
DEBUG:./logfile:2019-09-12 15:57:39,688:Initializing logger
DEBUG:./logfile:2019-09-12 15:57:39,689:Parsing header
DEBUG:./logfile:2019-09-12 15:57:39,693:Parsed 62 top-level labels
Traceback (most recent call last):
  File "bin/PDSView", line 21, in <module>
  File "/home/kelly/pds-view/eggs/PyInstaller-3.4-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "pds_view/View.py", line 3072, in <module>
  File "pds_view/View.py", line 3067, in main
  File "pds_view/View.py", line 3048, in __init__
  File "pds_view/View.py", line 699, in __init__
  File "pds_view/View.py", line 1158, in file_open
  File "pds_view/View.py", line 1138, in pds_file_check
  File "pds_view/Translate.py", line 204, in convert_to_pds4
UnboundLocalError: local variable 'offset' referenced before assignment
[31267] Failed to execute script PDSView
```

**Comment by root42** [comment]
Same problem happens on images from the LOIRP project: https://pds-imaging.jpl.nasa.gov/data/lo/LO_1001/
